repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.7
    hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    - id: mypy
      files: sphinx_needs/.*
      args: []
      additional_dependencies:
      - sphinx==6.2.1
      - docutils==0.19
      - types-docutils==0.20.0.20240201
      - types-jsonschema
      - types-requests

  - repo: local
    hooks:
      - id: check-readme
        name: check-readme
        files: README.rst
        language: python
        entry: rst2html.py README.rst --halt=warning
        pass_filenames: false
        additional_dependencies:
        - docutils==0.20.1
        - pygments
